Vagrant.configure(2) do |config|
  config.vm.box = "hbsmith/al2023"

  config.vm.provider "parallels" do |prl|
    prl.name = 'hbsmith-tabris'
    prl.cpus = 2
    prl.memory = 4096
  end

  config.vm.provision "shell",
    path: "provisioning.py",
    args: "vagrant",
    env: { "BRANCH" => ENV["BRANCH"] }
  config.vm.network "private_network", ip: "192.168.124.91", auto_config: false
end
